### ISSUE TITLE
Migrate model toolbox to python

### ISSUE THREAD

**Issue by srsjojo** [VTrans-Rail/Project-Web-GIS#3]
Hey Rick,

Just touching base. Have you gotten a chance to start implementing the toolbox as a single python script yet?

Thanks,
~stephen

**Comment by VTransRickScott** [comment]
Hi Stephen,

Looking at the the fields in the project table as they relate to domains, are you certain that all the valid values of a given domain will always be in the project table?  Specifically, looking at RailLineCode, AssetType, LocationType, & ProjectType, I could see a potential situation where all the valid values for one of these domains are not necessarily present in the data.  For example, you may not have a project on every valid rail line for the current year, correct?

**Comment by srsjojo** [comment]
Haha you're issuing all over the place... (probably could have been it's own since it doesn't really apply to the above discussion)

This is correct, I'm sorry if I made it confusing. The main domain which will need updated is the Project Name. The others can still be drawn from a CSV (or other source) because they won't change as often as the list of current projects.

**Comment by VTransRickScott** [comment]
Sorry, thought I closed this.  Have proceded with updating project domain from table, all other domains from their original sources (.CSVs).
