### ISSUE TITLE
Initial Build Complete.  Next Steps...

### ISSUE THREAD

**Issue by VTransRickScott** [VTrans-Rail/Project-Web-GIS#4]
Hi Stephen,

I've completed work on the script for the initial build, and the script appears to be building out the target objects correctly in my dev environment.  It looks like the next step is calculating VRLID, and updating the domains.  A few questions:  Are the domain updates repetitive, like the VRLID calculation?  If they are repetitive, is it okay to run them together (single script)?  There is no model builder script for the domain update - I'll need to build that from scratch, correct?  And just to verify, these domains are all coded values, correct?

Thanks!
Rick

**Comment by srsjojo** [comment]
Per phone:

- You can run the VRLID calculation and Domain creation in the same script
- You can delete the domains and repopulate and sort them based on a query of unique values that are in the projects feature class. 

Also: yes, they are coded value domains.

Thanks! :100:
