### ISSUE TITLE
Updating Domains: Coded Values vs. Descriptions

### ISSUE THREAD

**Issue by VTransRickScott** [VTrans-Rail/Project-Web-GIS#5]
Hi Stephen,

I just found an issue with updating the domains from the data.  Your coded values are different from your description.  ArcGIS is "smart" enough to display the description in place of the coded value.  The coded values are what is stored in the data, not the descriptions.  So if a new value is added to the data, it does not have a corresponding description.  If you want to update the domains from the data programmatically, you are probably going to want your coded values and descriptions to match.  Unless you have a better idea.

**Comment by srsjojo** [comment]
Hmmm, this is kind of frustrating. Does the "CODE" "field" have any limitations in SDE? Would the entire string below:
```
DuBois, Jeff Tucker Jtucker@DuBois-King.com (802)728-3376 (Main Office) (802)777-5264 (Jeff's Cell) - Pete Bero Pbero@DuBois-King.com (802)728-7213 (Pete's Direct) (617)571-9216 (Pete's Cell)
```
...be good to put in BOTH the "CODE" and "DESCRIPTION"? Is that overkill? Is there a best practice I should be following?

**Comment by VTransRickScott** [comment]
I'm finding anything related to "best practice".  What I would say is that, at a minimum, your code should be uniquely identifiable for querying purposes.  
Example of a bad scenario:
CODE        DESCRIPTION
Bernie        Bernie Chennette
Bernie        Bernie Backarack

Example of a good scenario:
CODE                DESCRIPTION
BChennette        Bernie Chennette
BBackarack        Bernie Backarack
JSmith                John Smith
JaSmith              Jane Smith
JASmith             John A Smith

With regard to your example above, because your fields are generally set to Text with a size of 255, and the snippet above is 192 characters, it'll fit just fine.  It becomes about validating the length of the input (a range domain?).

In the end, Description is a feature specific to the ESRI environment.  If you anticipate the need for your data to work in other non-ESRI environments, you need to plan for your coded values to work in those environments.

**Comment by srsjojo** [comment]
I'm not anticipating using these outside of Esri, but I take it Python won't see the description in a coded value domain?  If that's the case then I guess just put the exact same thing in both the CODE and DESCRIPTION fields

**Comment by VTransRickScott** [comment]
Actually, Python can read the description through the domain object.  Coded values are stored as a key/value pair, with coded value as the key, and description as the value.  That is not the problem.  The problem is that for new coded values, how would I get the entire pair?

**Comment by srsjojo** [comment]
Would it be simpler for now to just keep all the other domains updating out of their CSV so we can manually take care of those _occasional_ updates, and have your code update the `ProjectName` domain (since it's updated **frequently**) and put the same value in the `CODE` and `DESCRIPTION` fields? That's what it has now:

![image](https://cloud.githubusercontent.com/assets/7338435/5703670/a795b712-9a37-11e4-98ec-179b92037e7f.png)

**Comment by VTransRickScott** [comment]
Yup, I can do that.

Okay one last item.  Your contact field contains all the contact info for an individual.  From a DB purist standpoint, those items should be broken into individual fields in order to make them more manageable.  Personally, I'm ambivalent, but the 255 character limit on the field is hard, and if you end up needing to extend it, you'll have to go through some juggling to get there.  It's call for you Rail folks, I'm just your guide. :)

**Comment by TheMapSmith** [comment]
I agree completely, and it may be an area of expansion later, but it might also be dropped later, so for now let's just leave it.
