### ISSUE TITLE
Scripts Documentation

### ISSUE THREAD

**Issue by VTransRickScott** [VTrans-Rail/Project-Web-GIS#6]
Hi Stephen,

In the scripts documentation, under overview, you have this:

8_StatusUpdate_Append 7_AddProject Join Calculate DynSeg 4_Status Table Relate

However, in the steps, you have step 8 discreetly listed, and there is a step 9 (Dyn Seg Status).
8 & 9 are logical and flow, I'm not sure what you are getting at with the line above.  Is it a typo?

**Comment by srsjojo** [comment]
It looks like that's a MarkDown rendering error. The RAW file has them each on their own line. I fixed it.

However, it's a fair question why I have step 7 listed twice. My best guess is that the second step 7 in the overview is supposed to read "9_StatusUpdate_DynSeg". Obviously I mis-numbered step 4 when I was developing the process, but obviously the relate has to occur after creation. 

That makes me think: is setting up the relationship classes the last step in the "Setup" process? It doesn't really have to be a repetitive task if I understand relationship classes correctly.

**Comment by VTransRickScott** [comment]
Yeah, the relationship class wasn't on my radar.  I would agree that logically, it probably only needs to be built once, as long as the data integrity does not interfere with the post-processing.  Otherwise, it will have to be broken and rebuilt each time during post-processing.  I work on 8 & 9 next, then add the relationship class to the initial build and run the whole thing top to bottom, see what falls out.
